# Generated by Django 3.0.8 on 2020-07-30 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='p_diabetic',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='patient',
            name='p_gender',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
